server:
  port: 8080

spring:
  application:
    name: GATEWAY

  cloud:
    gateway:
      routes:

        - id: cliente
          uri: lb://CLIENTE
          predicates:
            - Path=/api/v1/clientes/**

        - id: moto
          uri: lb://MOTO
          predicates:
            - Path=/api/v1/motos/**

        - id: inventory
          uri: lb://INVENTORY
          predicates:
            - Path=/api/v1/inventory/**

        - id: venta
          uri: lb://VENTA
          predicates:
            - Path=/api/v1/ventas/**

        - id: pago
          uri: lb://PAGO
          predicates:
            - Path=/api/v1/pagos/**

        - id: notificacion
          uri: lb://NOTIFICACION
          predicates:
            - Path=/api/v1/notificaciones/**

        - id: factura
          uri: lb://FACTURA
          predicates:
            - Path=/api/v1/facturas/**

        - id: transporte
          uri: lb://TRANSPORTE
          predicates:
            - Path=/api/v1/transportes/**

        - id: destino
          uri: lb://DESTINO
          predicates:
            - Path=/api/v1/destino/**

        - id: envio
          uri: lb://ENVIO
          predicates:
            - Path=/api/v1/envios/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true

      